# .github/workflows/main.yml
# This workflow runs the Python script daily to send a Telegram notification.

name: Gold Price Telegram Notifier

on:
  # This trigger runs the workflow daily at a scheduled time
  schedule:
    # Runs at 12:30 PM (EEST) every day.
    # The cron expression is in UTC, so we subtract 3 hours from 15:30 UTC.
    # We choose this time because the prices are usually published after midday.
    - cron: '30 9 * * *'
  # This trigger allows for manual execution from the GitHub Actions UI
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager beautifulsoup4 requests


    - name: Run the Python script
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python gold_price_monitor.py
